//
// This is generated code. Do not edit this file.
//

package models

import play.api.libs.json._
import play.api.libs.functional.syntax._

object JsonOps {
  

  implicit val readsRangeSize: Reads[RangeSize] = (
    (__ \ "small").readNullable[Double] and
    (__ \ "large").readNullable[Double]
  )(RangeSize)

  implicit val writesRangeSize: Writes[RangeSize] = (
    (__ \ "small").writeNullable[Double] and
    (__ \ "large").writeNullable[Double]
  )(unlift(RangeSize.unapply))
         

       


  implicit val readsSize: Reads[Size] = (
    (__ \ "internationalSize").read[String] and
    (__ \ "neckSizeInch").read[RangeSize] and
    (__ \ "waist").read[Double] and
    (__ \ "manufacturer").read[Int] and
    (__ \ "chestInch").read[RangeSize]
  )(Size)

  implicit val writesSize: Writes[Size] = (
    (__ \ "internationalSize").write[String] and
    (__ \ "neckSizeInch").write[RangeSize] and
    (__ \ "waist").write[Double] and
    (__ \ "manufacturer").write[Int] and
    (__ \ "chestInch").write[RangeSize]
  )(unlift(Size.unapply))
         

       


  implicit val readsSizes: Reads[Sizes] =
    (__ \ "values").read[Seq[Size]].map(Sizes(_))

  implicit val writesSizes: Writes[Sizes] =
    (__ \ "values").write[Seq[Size]].contramap(_.values)
         

     
}
       
