//
// This is generated code. Do not edit this file.
//
package models


case class RangeSize(
  small: Option[Double] = None,
  large: Option[Double] = None
)
     

case class Size(
  internationalSize: String,
  neckSizeInch: RangeSize,
  waist: Double,
  manufacturer: Int,
  chestInch: RangeSize
)
     

case class Sizes(
  values: Seq[Size]
)
     
         
