//
// This is generated code. Do not edit this file.
//
package models


case class RangeSize(
  small: Option[Double] = None,
  large: Option[Double] = None
)
     

case class Size(
  internationalSize: Option[String] = None,
  waist: Option[Double] = None,
  chestInch: Option[RangeSize] = None,
  neckSizeInch: Option[RangeSize] = None,
  manufacturer: Option[Int] = None
)
     

case class Sizes(
  values: Option[Seq[Size]] = None
)
     
         
